FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends build-essential \
 python3.9 python3-dev python3-pip r-base
RUN ln -s /usr/bin/python3 /usr/bin/python

# Set container directory
WORKDIR /docker_rpy
# Copy files and directory structure
COPY . .
# Get necessary packages
RUN pip3 install -r code/requirements.txt
RUN Rscript code/packages.R
# Run
CMD code/instruction.sh
